core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
]

docx_format/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('format/', include('format.urls'))
]

format/urls.py
from django.urls import path
from format import views

app_name = 'format'

urlpatterns = [
    path('', views.format_docx, name='format')
]

core/models.py
from django.db import models

# Create your models here.

format/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render, redirect
from pathlib import Path
from django.conf import settings
from docx import Document
from django.http import FileResponse
from django.contrib import messages

def home(request):
    return render(
        request, 
        'core/home.html'
    )

def about(request):
    return render(
        request,
        'core/about.html'
    )

format/views.py
from pathlib import Path
from django.shortcuts import render, redirect
from django.conf import settings
from django.http import FileResponse
from django.http import Http404
from django.contrib import messages
from format.services.prepare_doc import prepare_to_format
from format.exceptions import TooLargeFileException, WrongFileExtensionException


def format_docx(request):
    if request.method == 'GET':
        return Http404
    else:
        doc = request.FILES.get('doc')
        hyphen = request.POST.get('hyphen')
        try:
            validate_document(doc)
            create_documents_dir_if_not_exists()
            formatted_doc = format_document(doc, hyphen)
            formatted_doc.save(f'{settings.MEDIA_ROOT}/documents/formatted.docx')
            return FileResponse(open(f'{settings.MEDIA_ROOT}/documents/formatted.docx', 'rb'))
        except TooLargeFileException as e:
            messages.error(request, e.message)
        except WrongFileExtensionException as e:
            messages.error(request, e.message)
        return redirect('core:home')
    

def validate_document(doc):
    if not doc:
        raise WrongFileExtensionException
    if doc.content_type != settings.VALID_EXTENSION:
        raise WrongFileExtensionException
    if doc.size > settings.MAX_DOCUMENT_SIZE:
        raise TooLargeFileException

def create_documents_dir_if_not_exists():
    document_dir = Path(f'{settings.MEDIA_ROOT}/documents')
    document_dir.mkdir(parents=True, exist_ok=True)

def format_document(doc, hyphen):
    if hyphen == 'on':
        hyphen = True
    else:
        hyphen = False
    formatted_doc = prepare_to_format(doc, hyphenation=hyphen)
    formatted_doc.style_document()
    return formatted_doc

core/templates/core/about.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="content">
        <p>На этом сайте вы можете оформить свою работу в формате docx в один клик.</p>
        <p>Просто загрузите документ, и одним нажатием на кнопку Оформить вы получите оформленную по ГОСТУ работу.</p>
    </div>
{% endblock %}

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
    {% block css_links %}
    {% endblock %}
    <title>Оформить работу</title>
</head>
<body class="stop-transition">
    <div class="container">
        {% include 'core/header.html' %}
        {% block content %}
        {% endblock %}
        {% include 'core/footer.html' %}
    </div>
    <script src="{% static 'core/js/main.js' %}"></script>
</body>
</html>

core/templates/core/burger.html
<div class="burger">
    <div class="bar bar--1"></div>
    <div class="bar bar--2"></div>
    <div class="bar bar--3"></div>
</div>

core/templates/core/drop_zone.html
{% load static %}
<div class="drop-zone--out">
    <div class="drop-zone--in">
        <div class="drop-zone__thumbnail hidden">
            <svg class="drop-zone__thumbnail-icon">
                <use xlink:href="{% static 'core/SVG/sprite.svg' %}#icon-file-text2"></use>
            </svg>
        </div>
        <div class="drop-zone__placeholder">
            <svg class="drop-zone__placeholder-icon">
                <use xlink:href="{% static 'core/SVG/sprite.svg' %}#icon-cloud-upload"></use>
            </svg>
            Перетащите файл или кликните для загрузки
        </div>
        <input type="file" name="doc" id="doc" class="drop-zone__input">
    </div>
</div>

core/templates/core/footer.html
<footer class="footer">
    <!-- <div class="form">
        <div class="form__form-group">
            <label for="email">Email:</label>
            <input type="email" name="email" id="email" class="form__text-input">
        </div>
        <div class="form__form-group">
            <label for="email">Отзыв или пожелание:</label>
            <textarea type="email" name="email" id="email" class="form__text-input" cols="40" rows="8"> 

            </textarea>
        </div>
        <button class="button" type="submit">Отправить</button>
    </div> -->
    <div class="footer__copyright">
        © 2020 Egor Poliakov
    </div>
    
</footer>

core/templates/core/header.html
{% load static %}
<header class="header">
    <div class="header__content">
        <div class="header__left">
            <h1 class="heading-main">
                Оформи работу в один клик
            </h1>
            <p class="paragraph paragraph--header">
                На этом сайте вы сможете оформить доклад или курсовую работу за несколько секунд!
            </p>
            <div class="header__features">
                <div class="header__feature">
                    <svg class="icon">
                        <use xlink:href="{% static 'core/SVG/sprite.svg' %}#icon-thumbs-up"></use>
                    </svg>
                    <div class="header__feature-text">
                        Наш услуги абсолютно бесплатны
                    </div>
                </div>
                <div class="header__feature">
                    <svg class="icon">
                        <use xlink:href="{% static 'core/SVG/sprite.svg' %}#icon-happy"></use>
                    </svg>
                    <div class="header__feature-text">
                        Оформление в один клик. Вам больше не нужно разбираться в функционале MS Word!
                    </div>
                </div>
            </div>
        </div>
        <div class="header__right">
            <ul class="header__list">
                <li class="header__list-item">
                    Загрузите свою работу
                </li>
                <li class="header__list-item">
                    Кликните на кнопку оформить
                </li>
                <li class="header__list-item">
                    Получите оформленную работу
                </li>
            </ul>
        </div>
    </div>
</header>

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
    <div class="instructions">
        <div class="instruction-card">
            <h3 class="instruction-card__heading">
                Подготовьте документ к оформлению
            </h3>
            <div class="instruction__content">
                Подготовьте документ к оформлению, следуя нескольким простым правилам
            </div>
            <svg class="instruction-card__icon">
                <use xlink:href="{% static 'core/SVG/sprite.svg' %}#icon-filter_1"></use>
            </svg>
        </div>
        <div class="instruction-card">
            <h3 class="instruction-card__heading">
                Загрузите документ в окно загрузки
            </h3>
            <div class="instruction__content">
                Загрузите документ, перетащив его или кликнув на окно загрузки
            </div>
            <svg class="instruction-card__icon">
                <use xlink:href="{% static 'core/SVG/sprite.svg' %}#icon-filter_2"></use>
            </svg>
        </div>
        <div class="instruction-card">
            <h3 class="instruction-card__heading">
                Нажмите кнопку "Оформить"
            </h3>
            <div class="instruction__content">
                Нажмите кнопку "Оформить" и получите оформленный документ
            </div>
            <svg class="instruction-card__icon">
                <use xlink:href="{% static 'core/SVG/sprite.svg' %}#icon-filter_3"></use>
            </svg>
        </div>
    </div>
    <div class="content">
        {% include 'core/messages.html' %}
        <form class="form" action="{% url 'format:format' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'core/drop_zone.html' %}
            <div class="form__form-group">
                <input type="checkbox" name="hyphen" id="hyphen">
                <label class="form__checkbox-label" for="hyphen">Автоперенос слов</label>
            </div>    
            <button class="button" type="submit">Оформить</button>
        </form>
    </div>
{% endblock %}

core/templates/core/instruction-card.html
{% load static %}
<div class="instruction-card">
    <h3 class="instruction-card__heading">
        {{ heading }}
    </h3>
    <div class="instruction__content">
        {{ content }}
    </div>
    <svg class="instruction-card__icon">
        <use xlink:href="{% static 'core/SVG/sprite.svg' %}#{{ icon }}"></use>
    </svg>
</div>

core/templates/core/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="message message--{{ message.tags }}">
            {{ message }}
        </div>   
    {% endfor %}
{% endif %}

core/templates/core/navbar.html
<nav class="nav">
    <ul class="nav__list">
        <li class="nav__item"><a class="nav__link" href="{% url 'core:about' %}">О сайте</a></li>
        <li class="nav__item"><a class="nav__link" href="{% url 'core:home' %}">Оформить работу</a></li>
    </ul>
    {% include 'core/burger.html' %}
</nav>